### PR TITLE
Update env path to point to correct anaconda folder

### PR DESCRIPTION
**Pull request by thala321**
Update env path to point to correct anaconda folder

### CODE REVIEW

**Comment by thala321** [comment]
My pull request for terraform is based on https://towardsdatascience.com/seamlessly-integrated-deep-learning-environment-with-terraform-google-cloud-gitlab-and-docker-faee4b351e94 @rohanchandra30 you might want to update the readme file with step by step guide

**Comment by thala321** [comment]
Basically we want to run to create a new server on google cloud (you can update it in the readme)

- terraform init

- terraform apply -auto-approve

Using terraform helps me a lot because I have limited fund to running these resources. So I have to run a lot of `terraform destroy` and `terraform deploy` :)

**Comment by thala321** [comment]
I could help writing two more terraform scripts to create new resources in AWS, Azure too if you want @rohanchandra30 . Choosing deployment to what ever cloud provider is up to the user

**Comment by rohanchandra30** [comment]
Sure. Go ahead with the terraform scripts, thanks ! Also, feel free to add the terraform Readme in the wiki. I'll review it once you're done and merge that as well.

**Pull request merged**
